/********************************************************************
* amd64_rhel60/EnergyFlowBranchesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error amd64_rhel60/EnergyFlowBranchesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEnergyFlowBranchesDict();
extern void G__cpp_setup_inheritanceEnergyFlowBranchesDict();
extern void G__cpp_setup_typetableEnergyFlowBranchesDict();
extern void G__cpp_setup_memvarEnergyFlowBranchesDict();
extern void G__cpp_setup_globalEnergyFlowBranchesDict();
extern void G__cpp_setup_memfuncEnergyFlowBranchesDict();
extern void G__cpp_setup_funcEnergyFlowBranchesDict();
extern void G__set_cpp_environmentEnergyFlowBranchesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel60/../EnergyFlowBranches.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EnergyFlowBranchesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_TTreeBranches;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_H1PartCandArrayPtr;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_H1FloatPtr;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_EnergyFlowBranches;
extern G__linked_taginfo G__EnergyFlowBranchesDictLN_EnergyFlowBranchescLcLdA;

/* STUB derived class for protected member access */
