/********************************************************************
* amd64_rhel60/TrackBranchesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error amd64_rhel60/TrackBranchesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTrackBranchesDict();
extern void G__cpp_setup_inheritanceTrackBranchesDict();
extern void G__cpp_setup_typetableTrackBranchesDict();
extern void G__cpp_setup_memvarTrackBranchesDict();
extern void G__cpp_setup_globalTrackBranchesDict();
extern void G__cpp_setup_memfuncTrackBranchesDict();
extern void G__cpp_setup_funcTrackBranchesDict();
extern void G__set_cpp_environmentTrackBranchesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel60/../TrackBranches.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TrackBranchesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TrackBranchesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrackBranchesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TrackBranchesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TrackBranchesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TrackBranchesDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TrackBranchesDictLN_TTreeBranches;
extern G__linked_taginfo G__TrackBranchesDictLN_H1PartCandArrayPtr;
extern G__linked_taginfo G__TrackBranchesDictLN_H1SelVertexArrayPtr;
extern G__linked_taginfo G__TrackBranchesDictLN_H1FSTFittedTrackArrayPtr;
extern G__linked_taginfo G__TrackBranchesDictLN_VertexBranches;
extern G__linked_taginfo G__TrackBranchesDictLN_TrackBranches;
extern G__linked_taginfo G__TrackBranchesDictLN_TrackBranchescLcLdA;

/* STUB derived class for protected member access */
