/********************************************************************
* amd64_rhel60/TriggerBranchesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error amd64_rhel60/TriggerBranchesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTriggerBranchesDict();
extern void G__cpp_setup_inheritanceTriggerBranchesDict();
extern void G__cpp_setup_typetableTriggerBranchesDict();
extern void G__cpp_setup_memvarTriggerBranchesDict();
extern void G__cpp_setup_globalTriggerBranchesDict();
extern void G__cpp_setup_memfuncTriggerBranchesDict();
extern void G__cpp_setup_funcTriggerBranchesDict();
extern void G__set_cpp_environmentTriggerBranchesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel60/../TriggerBranches.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TriggerBranchesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TriggerBranchesDictLN_TTreeBranches;
extern G__linked_taginfo G__TriggerBranchesDictLN_H1IntPtr;
extern G__linked_taginfo G__TriggerBranchesDictLN_H1BytePtr;
extern G__linked_taginfo G__TriggerBranchesDictLN_H1ShortPtr;
extern G__linked_taginfo G__TriggerBranchesDictLN_H1FloatPtr;
extern G__linked_taginfo G__TriggerBranchesDictLN_TriggerBranches;

/* STUB derived class for protected member access */
