// This file was automatically generated by the H1PtrGenerator class.
// ($Id: H1PtrGenerator.C,v 1.16 2005/12/02 11:22:34 katzy Exp $)
//_______________________
// data access class for TLorentzVector

#include "TLorentzVectorPtr.h"
#include "TLorentzVector.h"

ClassImp(TLorentzVectorPtr)


// con- and destructor

TLorentzVectorPtr::TLorentzVectorPtr(const char* branchName)
{
// create data access object for branch

  if (branchName)
    SetPointer(branchName);
  else
    fTreeObject = 0;
}


// access to pointer

Bool_t TLorentzVectorPtr::SetPointer(const char* branchName)
{
// set pointer to branch

  if (H1ObjectPtr::SetPointer(branchName)) {
    TObject* obj = *(TObject**)(GetBranch()->GetAddress());
    if (obj->InheritsFrom(TLorentzVector::Class())) return true;
    Error("SetPointer", "\n branch %s does not contain a TLorentzVector.\n", branchName);
  }
  fTreeObject = 0;
  return false;
}

TLorentzVector& TLorentzVectorPtr::operator *() const
{
// get reference to data
  return *(TLorentzVector*) GetPointer();
}

TLorentzVector* TLorentzVectorPtr::operator ->() const
{
// get pointer to data
  return (TLorentzVector*) GetPointer();
}
