/********************************************************************
* UserEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error UserEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUserEventDict();
extern void G__cpp_setup_inheritanceUserEventDict();
extern void G__cpp_setup_typetableUserEventDict();
extern void G__cpp_setup_memvarUserEventDict();
extern void G__cpp_setup_globalUserEventDict();
extern void G__cpp_setup_memfuncUserEventDict();
extern void G__cpp_setup_funcUserEventDict();
extern void G__set_cpp_environmentUserEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel70/../UserEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UserEventDictLN_TClass;
extern G__linked_taginfo G__UserEventDictLN_TBuffer;
extern G__linked_taginfo G__UserEventDictLN_TMemberInspector;
extern G__linked_taginfo G__UserEventDictLN_TObject;
extern G__linked_taginfo G__UserEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UserEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UserEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__UserEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__UserEventDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__UserEventDictLN_TLorentzVector;
extern G__linked_taginfo G__UserEventDictLN_TTree;
extern G__linked_taginfo G__UserEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__UserEventDictLN_H1Event;
extern G__linked_taginfo G__UserEventDictLN_UserEvent;

/* STUB derived class for protected member access */
