/********************************************************************
* amd64_rhel60/TLorentzVectorPtrDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error amd64_rhel60/TLorentzVectorPtrDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTLorentzVectorPtrDict();
extern void G__cpp_setup_inheritanceTLorentzVectorPtrDict();
extern void G__cpp_setup_typetableTLorentzVectorPtrDict();
extern void G__cpp_setup_memvarTLorentzVectorPtrDict();
extern void G__cpp_setup_globalTLorentzVectorPtrDict();
extern void G__cpp_setup_memfuncTLorentzVectorPtrDict();
extern void G__cpp_setup_funcTLorentzVectorPtrDict();
extern void G__set_cpp_environmentTLorentzVectorPtrDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel60/../TLorentzVectorPtr.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TClass;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TBuffer;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TMemberInspector;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TObject;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_H1Ptr;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_H1ObjectPtr;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TLorentzVector;
extern G__linked_taginfo G__TLorentzVectorPtrDictLN_TLorentzVectorPtr;

/* STUB derived class for protected member access */
