/********************************************************************
* amd64_rhel60/UserFillerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error amd64_rhel60/UserFillerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUserFillerDict();
extern void G__cpp_setup_inheritanceUserFillerDict();
extern void G__cpp_setup_typetableUserFillerDict();
extern void G__cpp_setup_memvarUserFillerDict();
extern void G__cpp_setup_globalUserFillerDict();
extern void G__cpp_setup_memfuncUserFillerDict();
extern void G__cpp_setup_funcUserFillerDict();
extern void G__set_cpp_environmentUserFillerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel60/../UserFiller.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UserFillerDictLN_TClass;
extern G__linked_taginfo G__UserFillerDictLN_TBuffer;
extern G__linked_taginfo G__UserFillerDictLN_TMemberInspector;
extern G__linked_taginfo G__UserFillerDictLN_TObject;
extern G__linked_taginfo G__UserFillerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UserFillerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserFillerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UserFillerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UserFillerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__UserFillerDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__UserFillerDictLN_H1EventFiller;
extern G__linked_taginfo G__UserFillerDictLN_H1Event;
extern G__linked_taginfo G__UserFillerDictLN_UserFiller;

/* STUB derived class for protected member access */
