/********************************************************************
* VertexBranchesDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error VertexBranchesDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableVertexBranchesDict();
extern void G__cpp_setup_inheritanceVertexBranchesDict();
extern void G__cpp_setup_typetableVertexBranchesDict();
extern void G__cpp_setup_memvarVertexBranchesDict();
extern void G__cpp_setup_globalVertexBranchesDict();
extern void G__cpp_setup_memfuncVertexBranchesDict();
extern void G__cpp_setup_funcVertexBranchesDict();
extern void G__set_cpp_environmentVertexBranchesDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "amd64_rhel70/../VertexBranches.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__VertexBranchesDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__VertexBranchesDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VertexBranchesDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__VertexBranchesDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VertexBranchesDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__VertexBranchesDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__VertexBranchesDictLN_TTreeBranches;
extern G__linked_taginfo G__VertexBranchesDictLN_H1SelVertexArrayPtr;
extern G__linked_taginfo G__VertexBranchesDictLN_VertexBranches;

/* STUB derived class for protected member access */
